---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'current' %>

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: debian-9.4
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  #
  # repository
  #
  - name: repository
    run_list:
      - recipe[test::repository]
  #
  # client_install
  #
  - name: client_install
    run_list:
      - recipe[test::client_install]
  #
  # server_install
  #
  - name: server_install
    run_list:
      - recipe[test::server_install]
